name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy    
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x    
          
      - name: SHow env var
        run: |
          echo $TELEGRAM_BOT_TOKEN    
        # ^ 
        # Reference by environment variable for added security
              
  
      - name: Upload to Deno Deploy       
        env:
           TELEGRAM_BOT_TOKEN: ${{ vars.TELEGRAM_BOT_TOKEN }}
        uses: denoland/deployctl@v1
        with:
          project: "quiet-parrot-65"
          entrypoint: "task.ts" # 📝 Update the entrypoint if necessary
          root: "." # 📝 Update the root if necessary
